version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: job-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:3.0
    container_name: job-system-localstack
    ports:
      - "4598:4598"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./scripts/init-queues.sh:/etc/localstack/init/ready.d/initsqs.sh"